Algoritmo "MULTVETAB"
// 3- Faça um algoritmo que preencha dois vetores com 5 posições cada.
//Em seguida leia dois vetores A e B , e após a leitura um novo vetor deve
//ser criado multiplicando os elementos dos mesmos índices e armazenando no
//novo vetor C, também no mesmo índice.
Var
// Declarações das variáveis


Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 


Fimalgoritmo