Algoritmo "VetorTeste"
//







Var
//Declarações das variáveis
x: vetor [0..3] de inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
x[0] <- 5
x[1] <- 10
x[2] <- 15
x[3] <- 20
 
escreval("Dados armazenados na pos. 0: ",x[0])
escreval("Dados armazenados na pos. 1: ",x[1])
escreval("Dados armazenados na pos. 2: ",x[2])
escreval("Dados armazenados na pos. 3: ",x[3])

Fimalgoritmo