Algoritmo "exercicio06"
// Faça um algoritmo que preencha uma matriz 10x10 e escreva a localização
//(a linha e a coluna) do maior valor.
Var
//Declarações das variáveis
mat: vetor[0..10,0..10] de inteiro;
i:inteiro;
j: inteiro;

Inicio
//Recebendo o valor da linha e da coluna
escreval("Informe o valor da linha: ")
leia (i)
escreval("Informe o valor da coluna: ")
leia (j)

//Laço for para identificação do maior valor

para i de 1 ate j faça





fimpara


Fimalgoritmo